# Generated by Django 5.0.3 on 2024-03-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_servings', models.IntegerField()),
                ('preparation_time', models.TimeField()),
                ('image', models.ImageField(upload_to='')),
                ('ingredients', models.TextField()),
                ('procedure', models.TextField()),
            ],
        ),
    ]
