# Generated by Django 5.0.3 on 2024-03-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_userrecipemapping_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipemapping',
            unique_together=set(),
        ),
    ]
