# Generated by Django 5.0.3 on 2024-03-29 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_userrecipemapping_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipecollectionmapping',
            unique_together={('user', 'user_recipe')},
        ),
    ]
